[01]
DefaultBaseUrl=                               #智谱AI开放平台获取的 API地址
[02]
apiKey=                                            #智谱AI开放平台获取的 API Key
[03]
Model=                                            #模型名称 (例如: glm-4-flash)
                                                        #这里默认为空使用的是作者提供的免费大模型，请配置自己使用的智谱清言大模型
